export const AUDI1 = {
  categories: [
    {
      name: 'Club',
      price: 300,
      rows: [
        {
          name: 'A', seats: [
            {
              no: 1,
              isAvailable: true,
              isBooked: false,
              isSelected: false,
              surgedPrice: 20,
            }, {
              no: 2,
              isAvailable: true,
              isBooked: false,
              isSelected: false,
              surgedPrice: 20,
            }, {
              no: 3,
              isAvailable: false,
              isBooked: true,
              isSelected: false
            }, {
              no: 4,
              isAvailable: false,
              isBooked: true,
              isSelected: false
            }, {
              no: 5,
              isAvailable: false,
              isBooked: true,
              isSelected: false
            }, {
              no: 6,
              isAvailable: false,
              isBooked: true,
              isSelected: false
            }, {
              no: 7,
              isAvailable: false,
              isBooked: true,
              isSelected: false
            }, {
              no: 8,
              isAvailable: false,
              isBooked: true,
              isSelected: false
            }, {
              no: 9,
              isAvailable: false,
              isBooked: true,
              isSelected: false
            }, {
              no: 10,
              isAvailable: false,
              isBooked: true,
              isSelected: false
            }, {
              no: 11,
              isAvailable: false,
              isBooked: true,
              isSelected: false
            }, {
              no: 12,
              isAvailable: false,
              isBooked: true,
              isSelected: false
            }, {
              no: 13,
              isAvailable: true,
              isBooked: false,
              isSelected: false
            }, {
              no: 14,
              isAvailable: true,
              isBooked: false,
              isSelected: false,
              surgedPrice: 20,
            }, {
              no: 15,
              isAvailable: true,
              isBooked: false,
              isSelected: false,
              surgedPrice: 20,
            } ]
        },
        {
          name: 'B', seats: [
            {}, {}, {
              no: 3,
              isAvailable: true,
              isBooked: false,
              isSelected: false
            }, {
              no: 4,
              isAvailable: true,
              isBooked: false,
              isSelected: false
            }, {
              no: 5,
              isAvailable: true,
              isBooked: false,
              isSelected: false
            }, {
              no: 6,
              isAvailable: true,
              isBooked: false,
              isSelected: false
            }, {
              no: 7,
              isAvailable: true,
              isBooked: false,
              isSelected: false
            }, {
              no: 8,
              isAvailable: true,
              isBooked: false,
              isSelected: false
            }, {
              no: 9,
              isAvailable: true,
              isBooked: false,
              isSelected: false
            }, {
              no: 10,
              isAvailable: true,
              isBooked: false,
              isSelected: false
            }, {
              no: 11,
              isAvailable: true,
              isBooked: false,
              isSelected: false
            }, {
              no: 12,
              isAvailable: true,
              isBooked: false,
              isSelected: false
            }, {
              no: 13,
              isAvailable: false,
              isBooked: true,
              isSelected: false
            }, {
              no: 14,
              isAvailable: false,
              isBooked: true,
              isSelected: false
            }, {
              no: 15,
              isAvailable: false,
              isBooked: true,
              isSelected: false
            } ]
        }
      ]
    },
    {
      name: 'Executive',
      price: 200,
      rows: [
        {
          name: 'C',
          seats: [ {}, {}, {}, {}, {}, {}, {
            no: 7,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 8,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 9,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 10,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 11,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 12,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 13,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 14,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 15,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          } ]
        },
        {
          name: 'D', seats: [ {}, {}, {}, {}, {}, {}, {
            no: 7,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 8,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 9,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 10,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 11,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 12,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 13,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 14,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 15,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          } ]
        },
        {
          name: 'E', seats: [ {}, {}, {}, {}, {}, {}, {
            no: 7,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 8,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 9,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 10,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 11,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 12,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 13,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 14,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 15,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          } ]
        },
        {
          name: 'F', seats: [ {}, {}, {}, {}, {}, {}, {
            no: 7,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 8,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 9,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 10,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 11,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 12,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 13,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 14,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 15,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          } ]
        },
        {
          name: 'G', seats: [ {
            no: 1,
            isAvailable: true,
            isBooked: false,
            isSelected: false
          }, {
            no: 2,
            isAvailable: true,
            isBooked: false,
            isSelected: false
          }, {
            no: 3,
            isAvailable: true,
            isBooked: false,
            isSelected: false
          }, {
            no: 4,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 5,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 6,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 7,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 8,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 9,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 10,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 11,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 12,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 13,
            isAvailable: true,
            isBooked: false,
            isSelected: false
          }, {
            no: 14,
            isAvailable: true,
            isBooked: false,
            isSelected: false
          }, {
            no: 15,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          } ]
        },
        {
          name: 'H', seats: [ {
            no: 1,
            isAvailable: true,
            isBooked: false,
            isSelected: false
          }, {
            no: 2,
            isAvailable: true,
            isBooked: false,
            isSelected: false
          }, {
            no: 3,
            isAvailable: true,
            isBooked: false,
            isSelected: false
          }, {
            no: 4,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 5,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 6,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 7,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 8,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 9,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 10,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 11,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 12,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 13,
            isAvailable: true,
            isBooked: false,
            isSelected: false
          }, {
            no: 14,
            isAvailable: true,
            isBooked: false,
            isSelected: false
          }, {
            no: 15,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          } ]
        },
        {
          name: 'I', seats: [ {
            no: 1,
            isAvailable: true,
            isBooked: false,
            isSelected: false
          }, {
            no: 2,
            isAvailable: true,
            isBooked: false,
            isSelected: false
          }, {
            no: 3,
            isAvailable: true,
            isBooked: false,
            isSelected: false
          }, {
            no: 4,
            isAvailable: true,
            isBooked: false,
            isSelected: false
          }, {
            no: 5,
            isAvailable: true,
            isBooked: false,
            isSelected: false
          }, {
            no: 6,
            isAvailable: true,
            isBooked: false,
            isSelected: false
          }, {
            no: 7,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 8,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 9,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 10,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 11,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 12,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 13,
            isAvailable: true,
            isBooked: false,
            isSelected: false
          }, {
            no: 14,
            isAvailable: true,
            isBooked: false,
            isSelected: false
          }, {
            no: 15,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          } ]
        },
        {
          name: 'J', seats: [ {
            no: 1,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 2,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 3,
            isAvailable: true,
            isBooked: false,
            isSelected: false
          }, {
            no: 4,
            isAvailable: true,
            isBooked: false,
            isSelected: false
          }, {
            no: 5,
            isAvailable: true,
            isBooked: false,
            isSelected: false
          }, {
            no: 6,
            isAvailable: true,
            isBooked: false,
            isSelected: false
          }, {
            no: 7,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 8,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 9,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 10,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 11,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 12,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          }, {
            no: 13,
            isAvailable: true,
            isBooked: false,
            isSelected: false
          }, {
            no: 14,
            isAvailable: true,
            isBooked: false,
            isSelected: false
          }, {
            no: 15,
            isAvailable: false,
            isBooked: true,
            isSelected: false
          } ]
        }
      ]
    }
  ]
};







